### ISSUE TITLE
 DYPA02YYUM delivers unstable reading

### ISSUE THREAD

**Issue by salasxhim** [ritesht93/waterproof_small_blind_ultrasonic_sensor_DYP-A02YYxx_v1.0#3]
DYPA02YYUM delivers unstable and wrong readingswith the code you provide
248cm
249cm
248cm
248cm
249cm
249cm
248cm
249cm
249cm
249cm
248cm
248cm
249cm
97cm
248cm
250cm
250cm
87cm
249cm
130cm
80cm
250cm
251cm
250cm
The exact distance is260cm

**Comment by riteshRcH** [comment]
Hi there, there could be a lot of factors affecting this. Can you let me know your exact setup?
